name: Deploy Next.js App

on:
  push:
    branches:
      - dev  # Déclenche le workflow sur les pushs vers la branche main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Build Next.js App
        run: yarn build

      - name: Deploy to Debian Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/debian/dev
            git pull origin dev
            yarn install
            yarn build
     