name: Deploy Next.js App

on:
  push:
    branches:
      - dev  # Déclenche le workflow sur les pushs vers la branche main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Deploy
        run: |
          TEMP=$(mktemp)
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $TEMP
          ssh -o 'StrictHostKeyChecking no' -i $TEMP debian@vps.latelier22.fr 'bash -s' < scripts/deploy.sh