/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {  useThree } from '@react-three/fiber'
import * as THREE from 'three'  // Importer Three.js


export function CadrePP(props) {
  const { nodes, materials } = useGLTF('/cadrePP.gltf')
  const { gl } = useThree()


 // Charger l'image pour le matériau du Node-Mesh_16
 const textureLoader = new THREE.TextureLoader()  // Utilisation de THREE.TextureLoader
 const texture = textureLoader.load('images/galerie-01-9.jpg')  // Remplacez par le chemin de votre image
 texture.wrapS = texture.wrapT = THREE.RepeatWrapping  // Options de répétition de la texture si nécessaire
 texture.repeat.set(1, 1)  // Paramètres de répétition de la texture si nécessaire
 texture.flipY = false
 texture.scale = 0.5
 texture.anisotropy = gl.capabilities.getMaxAnisotropy()
//  texture.needsUpdate = true

 // Créer un matériau avec la texture chargée
 // Créer un matériau avec la texture chargée
 const customMaterial = useRef(new THREE.MeshStandardMaterial({
   map: texture,
   transparent: false,  // Rend le matériau non transparent
   opacity: 1,          // Opacité maximale (complètement opaque)
 })).current



  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group_0.geometry}
          material={materials.Matière}
          
          scale={1.181}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group_2.geometry}
          material={materials.Color_D06}
          
          scale={1.181}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group_2001.geometry}
          material={materials.Color_D06}
          
          scale={1.181}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group_3.geometry}
          material={materials.Color_A05}
          
          scale={[1.181, 0.236, 1.181]}>
          <group scale={[0.847, 4.233, 0.847]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.ID43.geometry}
              material={materials.Color_I03}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.ID43_1.geometry}
              material={materials.Color_A05}
            />
          </group>
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.IMPRESSION.geometry}
          material={customMaterial}
          
          scale={[1.181, 0.236, 1.181]}
        />
      </group>
    </group>
  )
}

export default CadrePP

useGLTF.preload('/cadrePP.gltf')
