/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Palette(props) {
  const { nodes, materials } = useGLTF('/Palette.glb')
  return (
    <group {...props} dispose={null}>
      <group name="palette" rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          name="palette_1"
          castShadow
          receiveShadow
          geometry={nodes.palette_1.geometry}
          material={materials['01___Default']}
        />
        <mesh
          name="palette_2"
          castShadow
          receiveShadow
          geometry={nodes.palette_2.geometry}
          material={materials['04___Default']}
        />
        <mesh
          name="palette_3"
          castShadow
          receiveShadow
          geometry={nodes.palette_3.geometry}
          material={materials['03___Default']}
        />
        <mesh
          name="palette_4"
          castShadow
          receiveShadow
          geometry={nodes.palette_4.geometry}
          material={materials['11___Default']}
        />
        <mesh
          name="palette_5"
          castShadow
          receiveShadow
          geometry={nodes.palette_5.geometry}
          material={materials['02___Default']}
        />
        <mesh
          name="palette_6"
          castShadow
          receiveShadow
          geometry={nodes.palette_6.geometry}
          material={materials['05___Default']}
        />
        <mesh
          name="palette_7"
          castShadow
          receiveShadow
          geometry={nodes.palette_7.geometry}
          material={materials['10___Default']}
        />
      </group>
    </group>
  )
}

export default Palette


useGLTF.preload('/Palette.glb')