name: Deploy on push to shop

on:
  push:
    branches:
      - shop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: vps.latelier22.fr
          username: debian
          key: ${{ secrets.SSH_PRIVATE_KEY_MARCEL }}
          script: |
            cd /home/debian/marcel-de-mayotte.fr
            git pull origin shop
            echo "Installing dependencies..."
            pnpm install
            pnpm run build
            pm2 restart 0
            echo "Deployment completed successfully."

 
